config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :categories, only: [] do
    resources :sub_categories, only: :index
  end
  resources :orders

  get 'destgroups_order_categories' => 'order_categories#destgroups_order_categories', as: :destgroups_order_categories
  root 'items#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories, ->{ order(:id) }
  validates :name, presence: true
end

app/models/destgroup.rb
class Destgroup < ActiveRecord::Base
  has_and_belongs_to_many :orders
  has_and_belongs_to_many :services
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  belongs_to :sub_category
  validates :name, presence: true
  validates :category, :category_id, presence: true
  validates :sub_category, :sub_category_id, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_and_belongs_to_many :destgroups
  belongs_to :order_category
end

app/models/order_category.rb
class OrderCategory < ActiveRecord::Base
  has_many :service_order_category_links, dependent: :destroy
  has_many :services, through: :service_order_category_links
  has_many :orders, dependent: :nullify
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :parent_service, class_name: 'Service'
  has_many :child_services, class_name: 'Service', foreign_key: 'parent_service_id', dependent: :nullify
  has_many :service_order_category_links, dependent: :destroy
  has_many :order_categories, through: :service_order_category_links
  has_and_belongs_to_many :destgroups
end

app/models/service_order_category_link.rb
class ServiceOrderCategoryLink < ActiveRecord::Base
  belongs_to :service
  belongs_to :order_category
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  validates :name, presence: true
  validates :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def sub_categories
    category = Category.find(params[:category_id])
    render json: category.sub_categories.select(:id, :name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :category_id, :sub_category_id)
  end
end

app/controllers/order_categories_controller.rb
class OrderCategoriesController < ApplicationController
  def destgroups_order_categories
    p params[:id]
    destgroups = Destgroup.where(id: params[:id])
    render json: destgroups.joins(:services).joins('INNER JOIN service_order_category_links ON services.id = service_order_category_links.service_id').joins('INNER JOIN order_categories ON service_order_category_links.order_category_id = order_categories.id').select('order_categories.id, order_categories.name').distinct
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
    end
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:contract_number, :order_category_id, :destgroup_ids => [])
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def index
    category = Category.find(params[:category_id])
    render json: category.sub_categories.select(:id, :name)
  end
end

app/views/items/_form.html.slim
.row
  = bootstrap_form_for @item, html: {class: 'col-md-4'} do |f|
    = f.text_field :name

    - category_options = Category.order(:id).map { |c| [c.name, c.id, data: { children_path: category_sub_categories_path(c) }] }
    = f.select :category_id, category_options, { include_blank: true }, class: 'select-parent'

    - sub_categories = @item.category.try(:sub_categories) || []
    - sub_category_options = sub_categories.map { |c| [c.name, c.id] }
    = f.select :sub_category_id, sub_category_options, { include_blank: true }, class: 'select-children'

    = f.submit 'Save', class: 'btn btn-primary'

app/views/items/edit.html.slim
h1 Editing item

== render 'form'

=> link_to 'Show', @item
'|
= link_to 'Back', items_path

app/views/items/new.html.slim
h1 New item

== render 'form'

= link_to 'Back', items_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
/ add navigation links to this file

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Replace Selectbox Sandbox'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Replace Selectbox Sandbox'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      .container
        == render 'layouts/messages'
        == yield

app/views/orders/_form.html.slim
.row
  = bootstrap_form_for @order, html: {class: 'col-md-4'} do |f|
    = f.text_field :contract_number

    - destgroup_options = Destgroup.order(:id).map { |d| [d.name, d.id] }
    = f.select :destgroup_ids, destgroup_options, { include_blank: true }, { multiple: true, class: 'multiple-select-parent', "data-url" => destgroups_order_categories_path }

    - if @order.order_category
      - order_categories = @order.destgroups.joins(:services).joins('INNER JOIN service_order_category_links ON services.id = service_order_category_links.service_id').joins('INNER JOIN order_categories ON service_order_category_links.order_category_id = order_categories.id').select('order_categories.*')
    - else
      - order_categories = []

    - order_category_options = order_categories.map { |c| [c.name, c.id] }
    = f.select :order_category_id, order_category_options, { include_blank: true }, class: 'multiple-select-children'

    = f.submit 'Save', class: 'btn btn-primary'

app/views/orders/edit.html.slim
h1 収容依頼編集

== render 'form'

= link_to 'キャンセル', orders_path

app/views/orders/index.html.slim
h1 Listing orders

table.table
  thead
    tr
      th ContractNumber
      th OrderCategory
      th Sub category
      th
      th

  tbody
    - @orders.each do |order|
      tr
        td = order.contract_number
        td = order.order_category.name
        td = link_to 'Show', order
        td = link_to 'Edit', edit_order_path(order)
        td = link_to 'Destroy', order, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Item', new_order_path

app/views/orders/new.html.slim
h1 収容依頼作成

== render 'form'

= link_to 'キャンセル', orders_path

app/views/orders/show.html.slim
h1 Show order
p
  strong ContractNumber:
  =< @order.contract_number
p
  strong OrderCategory:
  =< @order.order_category.name
p
  strong Destgroup:
  - @order.destgroups.each do |destgroup|
    =< destgroup.name

=> link_to 'Edit', edit_order_path(@order)
'|
= link_to 'Back', orders_path